#!/bin/bash
function inputArray() {
    read -p "Enter the number of elements: " n
    for ((i = 0; i < n; i++)); 
        do
	read -p "a[$i] = " a[$i]
    done
}

function outputArray() {
    echo "Array values:"
    for ((i = 0; i < n; i++)); 
        do
	echo "${a[$i]}"
    done
}

function sumOddNums() {
    sum=0
    for ((i = 0; i < n; i++)); 
        do
	if (( ${a[$i]} % 2 != 0 )); 
        then
            sum=$((sum + ${a[$i]}))
        fi
    done
    echo "Sum of odd numbers: $sum"
}

function sortArray() {
    for ((i = 0; i < n - 1; i++)); 
        do
	for ((j = 0; j < n - i - 1; j++)); 
        do
            if ((a[j] > a[j+1])); 
                then
                temp=${a[j]}
                a[j]=${a[j+1]}
                a[j+1]=$temp
            fi
	done
    done
}

function minElement() {
    min=${a[0]}
    for ((i = 1; i < n; i++)); 
        do
	if (( ${a[$i]} < min )); 
                then
            min=${a[$i]}
        fi
    done
    echo "Minimum element: $min"
}

inputArray
outputArray
minElement
echo "After sorting:"
sortArray
outputArray
sumOddNums
